/**
 * The audio layer for Listening. Implements plan 011 step 1 and its STOP
 * condition.
 *
 * ## The audio decision, and why
 *
 * Plan 011 offered three options and refused to let code be written before one
 * was chosen. The choice is **option B: browser speech synthesis
 * (`window.speechSynthesis`), with option C — a fixed-pace transcript reveal —
 * as the fallback wherever no usable voice exists.** The reasoning, recorded
 * here so it is next to the code it governs:
 *
 *  - `speechSynthesis` is a built-in browser API, so it adds **no runtime
 *    dependency and no bundled bytes**. The app's stated "nothing beyond React"
 *    property survives intact, which no other option manages.
 *  - It **works offline**, like the rest of the app.
 *  - Bundling real recordings (option A) would add roughly **25–30 MB per
 *    test** to a 371 kB app. That is not a trade, it is a different product.
 *  - It is **honestly not the real exam**, and the UI says so in those words:
 *    the voice is synthetic, and the real test uses recorded speakers with
 *    varied accents (British, Australian, North American, New Zealand) which a
 *    platform voice will not reproduce. See `SYNTHETIC_VOICE_NOTICE`.
 *  - Where the platform offers no usable voice, `TranscriptPaceDriver` reveals
 *    the transcript cue by cue at a fixed speaking pace rather than silently
 *    doing nothing — plan 011's STOP condition, discharged.
 *
 * ## Plan 032: picking a GOOD synthetic voice
 *
 * Plan 011 chose option B and stopped there — `pickVoice` took the first
 * platform voice that matched a language, which is reliably the platform's
 * WORST voice (compact/legacy voices are listed first; "Natural"/"Neural"
 * ones come later). Plan 032 fixes that in place, still inside option B's
 * budget of zero bundled bytes:
 *
 *  - `pickVoice`/`rankVoices` score every candidate instead of taking the
 *    first match, so a high-quality installed voice actually gets used.
 *  - `assignSectionVoices` gives a section's different speakers different
 *    voices where the platform offers more than one usable match, and a
 *    pitch offset where it does not — a two-speaker conversation stops being
 *    one voice talking to itself.
 *  - A learner can override the automatic choice from the Listening picker;
 *    the choice is `preferredVoiceURI` in `src/profile/prefs.ts`, read here at
 *    driver construction (see `createSpeechDriver`), never on every play.
 *
 * ## Why there is an interface at all
 *
 * `SpeechDriver` exists so the runner can be tested **without a speech engine**.
 * `speechSynthesis` does not exist in jsdom or in Node, it is asynchronous, it
 * is famously flaky across platforms, and nothing about the play-once rule or
 * section ordering has anything to do with it. `FakeSpeechDriver` is
 * deterministic, uses no timers and records what it was asked to say, so the
 * engine tests can assert on playback without ever touching a browser global.
 *
 * Nothing in this file touches a global at import time. It is imported by tests
 * that run in the Node environment.
 */
import type { ListeningSection, ListeningVoiceHint } from './types'
import { loadPrefs } from '../profile/prefs'

/* ---------------------------------- notices --------------------------------- */

/**
 * What the UI must tell the learner about the audio, in plain words.
 *
 * Exported as a constant rather than typed into a component so that it cannot
 * quietly go missing: it is the honesty half of the audio decision, and a
 * Listening screen that plays a synthetic voice without saying so is
 * misrepresenting how close the practice is to the exam.
 */
export const SYNTHETIC_VOICE_NOTICE =
  'This voice is generated by your browser, not a recording. The real IELTS ' +
  'Listening test uses actors recorded in a studio, with British, Australian, ' +
  'North American and New Zealand accents. Treat this as practice for the ' +
  'question types and note-taking, not for accents.'

/** Shown when no usable voice exists and the transcript is revealed instead. */
export const TRANSCRIPT_FALLBACK_NOTICE =
  'Your browser has no speech voice available, so the transcript is being ' +
  'revealed line by line at speaking pace instead. This is a reading exercise ' +
  'with a clock on it, not a listening one — be aware of the difference.'

/* ----------------------------------- cues ----------------------------------- */

/** One thing to say, flattened out of a transcript for playback. */
export interface SpeechCue {
  /** `ListeningCue.id`. */
  id: string
  /** Speaker label to display, e.g. 'ROSS'. */
  speaker: string
  text: string
  /** Silence before this cue, in seconds. */
  pauseBeforeSec?: number
  /** How the speaker should sound, when the driver can honour it. */
  voice?: ListeningVoiceHint
}

/**
 * Flatten a section's transcript into a playback queue.
 *
 * Pure and total. A cue naming a speaker the section never declared is still
 * played — with its raw id as the label — rather than dropped: losing a line of
 * the recording because of a typo in a content file would cost the learner a
 * mark and give no clue why. `tests/listening-marking.test.ts` catches the typo
 * instead.
 */
export function sectionCues(section: ListeningSection): SpeechCue[] {
  const byId = new Map(section.transcript.speakers.map((speaker) => [speaker.id, speaker]))

  return section.transcript.cues.map((cue) => {
    const speaker = byId.get(cue.speakerId)
    return {
      id: cue.id,
      speaker: speaker?.label ?? cue.speakerId,
      text: cue.text,
      pauseBeforeSec: cue.pauseBeforeSec,
      voice: speaker?.voice,
    }
  })
}

/* --------------------------------- the driver -------------------------------- */

export type SpeechDriverKind = 'speech-synthesis' | 'transcript-pace' | 'fake'

/**
 * How a playback ended.
 *
 * `unavailable` is distinct from `cancelled` on purpose: the first means the
 * learner heard nothing through no fault of their own and the UI owes them an
 * explanation, the second means they stopped it.
 */
export type SpeechOutcome = 'completed' | 'cancelled' | 'unavailable'

/** Progress reports during playback. Every handler is optional. */
export interface SpeechEvents {
  onCueStart?: (cue: SpeechCue, index: number) => void
  onCueEnd?: (cue: SpeechCue, index: number) => void
  onOutcome?: (outcome: SpeechOutcome) => void
}

/**
 * Something that can say a queue of cues out loud, in order.
 *
 * Deliberately tiny. There is no pause, no seek and no rate control on the
 * interface because the exam has none of them: the recording plays once,
 * straight through. A driver that offered seeking would let a runner build a
 * feature the exam does not have.
 */
export interface SpeechDriver {
  readonly kind: SpeechDriverKind
  /** Can this driver actually produce output right now? */
  available(): boolean
  /**
   * Speak every cue in order. Resolves once the last one finishes, or as soon
   * as playback is cancelled or found to be impossible. Never rejects.
   */
  play(cues: readonly SpeechCue[], events?: SpeechEvents): Promise<SpeechOutcome>
  /** Stop immediately. Safe to call when nothing is playing. */
  cancel(): void
}

/* -------------------------------- scheduling -------------------------------- */

/**
 * Delayed execution, injectable so the paced driver can be driven by a fake
 * clock in a test rather than by real seconds.
 */
export interface SpeechScheduler {
  /** Run `fn` after `ms`. Returns a function that cancels it. */
  after(ms: number, fn: () => void): () => void
}

/** The real clock. */
export const realScheduler: SpeechScheduler = {
  after(ms, fn) {
    const handle: ReturnType<typeof setTimeout> = setTimeout(fn, ms)
    return () => clearTimeout(handle)
  },
}

/**
 * Speaking pace of the fallback driver, in words per minute.
 *
 * IELTS Listening recordings run at roughly 120–150 wpm depending on the
 * section and the speaker. 130 sits inside that band and is deliberately not
 * adjustable per cue: a fallback that let the learner slow the transcript down
 * would be training a skill the exam does not test.
 */
export const TRANSCRIPT_PACE_WPM = 130

/** How long a cue should take at a given pace. Zero for empty text. */
export function cueDurationMs(text: string, wordsPerMinute: number = TRANSCRIPT_PACE_WPM): number {
  const words = text.trim().split(/\s+/).filter((word) => word.length > 0).length
  if (words === 0) return 0

  const pace = wordsPerMinute > 0 ? wordsPerMinute : TRANSCRIPT_PACE_WPM
  return Math.round((words / pace) * 60_000)
}

/* -------------------------- browser speech synthesis ------------------------- */

/** The slice of `window.speechSynthesis` this module uses. */
export interface SpeechSynthesisLike {
  speak(utterance: SpeechSynthesisUtterance): void
  cancel(): void
  getVoices(): SpeechSynthesisVoice[]
}

/** The synthesiser plus the utterance constructor, injectable as a pair. */
export interface SpeechEngine {
  synthesis: SpeechSynthesisLike
  createUtterance(text: string): SpeechSynthesisUtterance
}

/**
 * The browser's engine, or null where there is not one.
 *
 * Reads its globals through `globalThis` inside the function body, so importing
 * this module in Node — which every engine test does — touches nothing.
 */
export function browserSpeechEngine(): SpeechEngine | null {
  const scope = globalThis as {
    speechSynthesis?: SpeechSynthesisLike
    SpeechSynthesisUtterance?: new (text: string) => SpeechSynthesisUtterance
  }

  const synthesis = scope.speechSynthesis
  const Utterance = scope.SpeechSynthesisUtterance
  if (synthesis === undefined || Utterance === undefined) return null

  return { synthesis, createUtterance: (text) => new Utterance(text) }
}

/* ------------------------------- voice ranking ------------------------------- */

/**
 * Voice-NAME substrings that tend to mark a modern, natural-sounding voice —
 * "Microsoft Sonia Online (Natural)", "Google UK English Female", a Siri
 * voice, an Edge "… Neural" voice, and so on.
 *
 * This is a HEURISTIC, not a lookup table, and platforms rename and reshuffle
 * their voice lists across OS and browser versions — it WILL rot. That is why
 * "Automatic" must always be a safe, working default even on the day every
 * marker below is stale: the ranking only ever changes WHICH installed voice
 * gets picked, never whether picking one can fail.
 */
export const QUALITY_VOICE_MARKERS = [
  'natural',
  'neural',
  'premium',
  'enhanced',
  'siri',
  'google',
  'aria',
  'sonia',
  'libby',
  'ryan',
] as const

/**
 * Voice-NAME substrings that tend to mark a legacy, compact or robotic voice —
 * the ones platforms keep shipping for compatibility but stopped putting
 * first. Same heuristic caveat as `QUALITY_VOICE_MARKERS`: it will rot, and
 * nothing here is allowed to make voice selection able to fail.
 */
export const LEGACY_VOICE_MARKERS = [
  'compact',
  'espeak',
  'eloquence',
  'albert',
  'zarvox',
  'fred',
  'whisper',
  'bells',
] as const

/**
 * The name-based half of a voice's score: +4 for a quality marker, −4 for a
 * legacy one, both checked case-insensitively as substrings. A name can only
 * match one list in practice (the marker lists do not overlap), but nothing
 * here assumes that — a name matching both would net to 0, which is exactly
 * "no opinion", the correct answer for a heuristic that contradicts itself.
 */
export function voiceQualityScore(voice: SpeechSynthesisVoice): number {
  const name = voice.name.toLowerCase()
  let score = 0
  if (QUALITY_VOICE_MARKERS.some((marker) => name.includes(marker))) score += 4
  if (LEGACY_VOICE_MARKERS.some((marker) => name.includes(marker))) score -= 4
  return score
}

/**
 * Every voice usable for a hint, best first.
 *
 * "Usable" means the same PRIMARY language as the hint (`'en'` for `'en-GB'`)
 * — anything else is a voice that would read the transcript in the wrong
 * language, which is worse than no voice at all. Among usable voices: +3 for
 * an exact BCP-47 match (`'en-gb'` for an `'en-GB'` hint) over +1 for a
 * same-primary-language voice in a different territory, plus
 * `voiceQualityScore`. Ties keep the platform's own list order — the one
 * thing that is stable across a browser session.
 *
 * `preferredVoiceURI`, when it names a voice present in the result, is moved
 * to the front — chosen BY the ranking rather than instead of it, so a
 * learner's explicit pick still leaves the rest of the list in quality order
 * for `assignSectionVoices` to hand to the section's other speakers. A URI
 * that matches nothing (the platform no longer has that voice) changes
 * nothing — the automatic ranking stands, silently. That silence is the
 * fallback plan 032 asks for: a vanished preference is never an error.
 */
export function rankVoices(
  voices: readonly SpeechSynthesisVoice[],
  hint: ListeningVoiceHint,
  preferredVoiceURI?: string,
): SpeechSynthesisVoice[] {
  const wanted = hint.accent.toLowerCase().replace('_', '-')
  const primary = wanted.split('-')[0]

  const ranked = voices
    .map((voice, index) => ({ voice, index }))
    .filter(({ voice }) => voice.lang.toLowerCase().replace('_', '-').startsWith(primary))
    .map(({ voice, index }) => ({
      voice,
      index,
      score: (voice.lang.toLowerCase().replace('_', '-') === wanted ? 3 : 1) + voiceQualityScore(voice),
    }))
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .map((entry) => entry.voice)

  if (preferredVoiceURI === undefined) return ranked
  const preferredAt = ranked.findIndex((voice) => voice.voiceURI === preferredVoiceURI)
  if (preferredAt <= 0) return ranked // not found, or already first — nothing to move.

  const preferred = ranked[preferredAt]
  return [preferred, ...ranked.slice(0, preferredAt), ...ranked.slice(preferredAt + 1)]
}

/**
 * Pick a voice for a cue.
 *
 * Best effort and nothing more: the top of `rankVoices`, or `null` where the
 * platform has nothing usable at all. It never fails. This is the SINGLE-cue
 * decision; `assignSectionVoices` is what gives a section's several speakers
 * distinct voices instead of all reaching this same top pick.
 */
export function pickVoice(
  voices: readonly SpeechSynthesisVoice[],
  hint: ListeningVoiceHint | undefined,
): SpeechSynthesisVoice | null {
  if (hint === undefined) return null
  return rankVoices(voices, hint)[0] ?? null
}

/** Pitch nudge applied when a section's speakers cannot be told apart by
 *  VOICE (the platform offers fewer usable matches than speakers) — the
 *  fallback differentiator, alternating by speaker so adjacent turns are not
 *  literally the same voice. `ListeningVoiceHint.pitch` (`types.ts`) is
 *  "relative to the driver's default, 1 leaves it alone", so this is added to
 *  whatever the hint or the default already specifies, never replaces it. */
const PITCH_DIFFERENTIATION = 0.15

/** What a section's playback actually uses for one speaker. */
interface ResolvedVoice {
  voice: SpeechSynthesisVoice | null
  pitchOffset: number
}

/**
 * Assign each of a section's speakers a voice, distinct from the others where
 * the platform allows it.
 *
 * `sectionCues` already carries each cue's speaker hint, but calling
 * `pickVoice` independently per cue has no memory across cues — two speakers
 * who share a hint (the common case: two `en-GB` characters in a phone call)
 * got the SAME top-ranked voice, because nothing recorded that a voice had
 * already been "spent" on someone else. This groups a section's speakers by
 * hint accent, ranks each group once (`rankVoices`, so "distinct" never means
 * "worse"), and round-robins the ranked candidates across the speakers who
 * share that accent, in the order they are first passed in (`speakers`
 * preserves `Map` insertion order, and callers build it in first-appearance
 * order — see `SpeechSynthesisDriver.play`).
 *
 * When an accent group has fewer than two usable voices, there is no second
 * voice to hand out — the fallback is `PITCH_DIFFERENTIATION`, alternating by
 * speaker, so a phone call between two people does not sound like one person
 * quoting themselves. A section with only one speaker gets no pitch nudge at
 * all: there is nobody for them to be told apart FROM.
 *
 * Voice GENDER is never inferred from a voice's NAME to break a tie here —
 * name lists are locale-dependent (a "female-sounding" English name on one
 * platform's voice list is a man's voice on another) and wrong often enough
 * to be worse than the pitch nudge. `ListeningVoiceHint.gender` exists for
 * the UI and for a future driver with real per-gender voices, not for this
 * one to pattern-match on.
 */
export function assignSectionVoices(
  voices: readonly SpeechSynthesisVoice[],
  speakers: ReadonlyMap<string, ListeningVoiceHint>,
  preferredVoiceURI?: string,
): Map<string, ResolvedVoice> {
  const resolved = new Map<string, ResolvedVoice>()
  const singleSpeaker = speakers.size <= 1
  const groups = new Map<string, { ranked: SpeechSynthesisVoice[]; nextIndex: number }>()

  for (const [speakerKey, hint] of speakers) {
    const accentKey = hint.accent.toLowerCase()
    let group = groups.get(accentKey)
    if (group === undefined) {
      group = { ranked: rankVoices(voices, hint, preferredVoiceURI), nextIndex: 0 }
      groups.set(accentKey, group)
    }

    const useIndex = group.nextIndex
    group.nextIndex += 1

    if (group.ranked.length >= 2) {
      resolved.set(speakerKey, { voice: group.ranked[useIndex % group.ranked.length], pitchOffset: 0 })
      continue
    }

    resolved.set(speakerKey, {
      voice: group.ranked[0] ?? null,
      pitchOffset: singleSpeaker ? 0 : useIndex % 2 === 0 ? PITCH_DIFFERENTIATION : -PITCH_DIFFERENTIATION,
    })
  }

  return resolved
}

/** Keep an utterance pitch inside the range `SpeechSynthesisUtterance.pitch`
 *  actually accepts. Pitch offsets are additive (see `PITCH_DIFFERENTIATION`),
 *  so a value near either end of the range must not walk off it. */
function clampPitch(pitch: number): number {
  return Math.min(2, Math.max(0, pitch))
}

/**
 * Speaks through the browser.
 *
 * One utterance at a time, chained on `onend`, because queueing the whole
 * section into `speechSynthesis` at once loses the ability to report which cue
 * is being spoken and makes cancellation ragged. An utterance that errors is
 * treated as finished rather than fatal: one mangled line is better than a
 * section that stops halfway with no explanation.
 *
 * `preferredVoiceURI` is read ONCE, at construction (`createSpeechDriver`
 * reads it from `src/profile/prefs.ts` and passes it in here) — never
 * re-read mid-play, so a section's voices cannot change out from under a
 * learner who is halfway through listening to it.
 */
export class SpeechSynthesisDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'speech-synthesis'

  private engine: SpeechEngine | null
  private cancelled = false

  constructor(
    engine: SpeechEngine | null = browserSpeechEngine(),
    private readonly preferredVoiceURI?: string,
  ) {
    this.engine = engine
  }

  available(): boolean {
    return this.engine !== null
  }

  cancel(): void {
    this.cancelled = true
    this.engine?.synthesis.cancel()
  }

  play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    const engine = this.engine
    if (engine === null) {
      events.onOutcome?.('unavailable')
      return Promise.resolve<SpeechOutcome>('unavailable')
    }

    this.cancelled = false

    // Each of THIS section's speakers gets a voice assigned once, up front,
    // so a speaker with several cues keeps the same voice throughout instead
    // of re-rolling it cue by cue — see `assignSectionVoices`.
    const speakerHints = new Map<string, ListeningVoiceHint>()
    for (const cue of cues) {
      if (cue.voice !== undefined && !speakerHints.has(cue.speaker)) {
        speakerHints.set(cue.speaker, cue.voice)
      }
    }
    const assigned = assignSectionVoices(
      engine.synthesis.getVoices(),
      speakerHints,
      this.preferredVoiceURI,
    )

    return new Promise<SpeechOutcome>((resolve) => {
      const finish = (outcome: SpeechOutcome): void => {
        events.onOutcome?.(outcome)
        resolve(outcome)
      }

      const speakFrom = (index: number): void => {
        if (this.cancelled) return finish('cancelled')
        if (index >= cues.length) return finish('completed')

        const cue = cues[index]
        const utterance = engine.createUtterance(cue.text)
        const resolved = cue.voice === undefined ? undefined : assigned.get(cue.speaker)
        if (resolved?.voice != null) utterance.voice = resolved.voice
        if (cue.voice?.rate !== undefined) utterance.rate = cue.voice.rate
        const pitchOffset = resolved?.pitchOffset ?? 0
        if (cue.voice?.pitch !== undefined || pitchOffset !== 0) {
          utterance.pitch = clampPitch((cue.voice?.pitch ?? 1) + pitchOffset)
        }

        let advanced = false
        const advance = (): void => {
          if (advanced) return
          advanced = true
          events.onCueEnd?.(cue, index)
          speakFrom(index + 1)
        }

        utterance.onend = advance
        // An engine error ends the line, not the section.
        utterance.onerror = advance

        events.onCueStart?.(cue, index)
        engine.synthesis.speak(utterance)
      }

      speakFrom(0)
    })
  }
}

/* ---------------------------- transcript fallback ---------------------------- */

/**
 * The fallback: reveal the transcript one cue at a time at a fixed pace.
 *
 * Plan 011's option C, used only where option B has no voice to work with. It
 * is honest about being a different exercise (`TRANSCRIPT_FALLBACK_NOTICE`) and
 * it holds the one property that makes it worth having: the learner cannot go
 * back, and the text moves on whether they are ready or not.
 */
export class TranscriptPaceDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'transcript-pace'

  private cancelTimer: (() => void) | null = null
  private cancelled = false

  constructor(
    private readonly scheduler: SpeechScheduler = realScheduler,
    private readonly wordsPerMinute: number = TRANSCRIPT_PACE_WPM,
  ) {}

  /** Always. Revealing text needs nothing from the platform. */
  available(): boolean {
    return true
  }

  cancel(): void {
    this.cancelled = true
    this.cancelTimer?.()
    this.cancelTimer = null
  }

  play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    this.cancelled = false

    return new Promise<SpeechOutcome>((resolve) => {
      const finish = (outcome: SpeechOutcome): void => {
        this.cancelTimer = null
        events.onOutcome?.(outcome)
        resolve(outcome)
      }

      const revealFrom = (index: number): void => {
        if (this.cancelled) return finish('cancelled')
        if (index >= cues.length) return finish('completed')

        const cue = cues[index]
        const pause = Math.max(0, (cue.pauseBeforeSec ?? 0) * 1000)
        const spoken = cueDurationMs(cue.text, this.wordsPerMinute)

        this.cancelTimer = this.scheduler.after(pause, () => {
          if (this.cancelled) return finish('cancelled')
          events.onCueStart?.(cue, index)

          this.cancelTimer = this.scheduler.after(spoken, () => {
            if (this.cancelled) return finish('cancelled')
            events.onCueEnd?.(cue, index)
            revealFrom(index + 1)
          })
        })
      }

      revealFrom(0)
    })
  }
}

/* ------------------------------- the test double ----------------------------- */

export interface FakeSpeechDriverOptions {
  /** Report no usable voice. Playback then speaks nothing. Defaults to true. */
  available?: boolean
  /** Cancel once this many cues have started, to exercise the cancelled path. */
  cancelAfterCues?: number
}

/**
 * A deterministic `SpeechDriver` for tests.
 *
 * No timers, no globals, no randomness: `play` walks the queue synchronously,
 * fires the same events a real driver fires, and resolves on the next
 * microtask. It records every cue it spoke and every outcome it reported, which
 * is what makes "the sections played in order, and each one reported
 * completion" an assertion rather than a hope.
 */
export class FakeSpeechDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'fake'

  /** Every cue actually spoken, across every `play` call, in order. */
  readonly spoken: SpeechCue[] = []
  /** One entry per `play` call, in call order. */
  readonly outcomes: SpeechOutcome[] = []
  /** One entry per `play` call: the cue ids it was handed. */
  readonly queues: string[][] = []

  private readonly isAvailable: boolean
  private readonly cancelAfterCues: number | null
  private cancelled = false

  constructor(options: FakeSpeechDriverOptions = {}) {
    this.isAvailable = options.available ?? true
    this.cancelAfterCues = options.cancelAfterCues ?? null
  }

  available(): boolean {
    return this.isAvailable
  }

  cancel(): void {
    this.cancelled = true
  }

  async play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    this.queues.push(cues.map((cue) => cue.id))

    if (!this.isAvailable) {
      this.outcomes.push('unavailable')
      events.onOutcome?.('unavailable')
      return 'unavailable'
    }

    this.cancelled = false
    let outcome: SpeechOutcome = 'completed'

    for (let index = 0; index < cues.length; index += 1) {
      if (this.cancelled) {
        outcome = 'cancelled'
        break
      }

      const cue = cues[index]
      events.onCueStart?.(cue, index)
      this.spoken.push(cue)

      if (this.cancelAfterCues !== null && this.spoken.length >= this.cancelAfterCues) {
        this.cancelled = true
      }

      if (this.cancelled) {
        outcome = 'cancelled'
        break
      }

      events.onCueEnd?.(cue, index)
    }

    this.outcomes.push(outcome)
    events.onOutcome?.(outcome)
    return outcome
  }

  /** The text of everything spoken so far, for assertions on content. */
  spokenText(): string[] {
    return this.spoken.map((cue) => cue.text)
  }
}

/* -------------------------------- construction ------------------------------- */

export interface CreateSpeechDriverOptions {
  /** Override the engine, e.g. to force the fallback. Defaults to the browser's. */
  engine?: SpeechEngine | null
  scheduler?: SpeechScheduler
  wordsPerMinute?: number
}

/**
 * The driver this platform can actually use: the browser's synthesiser where
 * there is one, the paced transcript where there is not.
 *
 * The choice is made once, at construction, and the caller can see which it got
 * from `driver.kind` — which is how the UI knows whether to show
 * `SYNTHETIC_VOICE_NOTICE` or `TRANSCRIPT_FALLBACK_NOTICE`.
 *
 * `preferredVoiceURI` (plan 032) is read from `src/profile/prefs.ts` HERE,
 * once, and threaded into `SpeechSynthesisDriver` — the driver itself never
 * imports `prefs.ts`, keeping it constructor-testable like every other driver
 * in this file.
 */
export function createSpeechDriver(options: CreateSpeechDriverOptions = {}): SpeechDriver {
  const engine = options.engine !== undefined ? options.engine : browserSpeechEngine()
  const preferredVoiceURI = loadPrefs().preferredVoiceURI
  if (engine !== null) return new SpeechSynthesisDriver(engine, preferredVoiceURI)

  return new TranscriptPaceDriver(
    options.scheduler ?? realScheduler,
    options.wordsPerMinute ?? TRANSCRIPT_PACE_WPM,
  )
}

/** The notice a driver's kind obliges the UI to show. */
export function noticeFor(kind: SpeechDriverKind): string {
  return kind === 'transcript-pace' ? TRANSCRIPT_FALLBACK_NOTICE : SYNTHETIC_VOICE_NOTICE
}
