/**
 * The audio layer for Listening. Implements plan 011 step 1 and its STOP
 * condition.
 *
 * ## The audio decision, and why
 *
 * Plan 011 offered three options and refused to let code be written before one
 * was chosen. The choice is **option B: browser speech synthesis
 * (`window.speechSynthesis`), with option C — a fixed-pace transcript reveal —
 * as the fallback wherever no usable voice exists.** The reasoning, recorded
 * here so it is next to the code it governs:
 *
 *  - `speechSynthesis` is a built-in browser API, so it adds **no runtime
 *    dependency and no bundled bytes**. The app's stated "nothing beyond React"
 *    property survives intact, which no other option manages.
 *  - It **works offline**, like the rest of the app.
 *  - Bundling real recordings (option A) would add roughly **25–30 MB per
 *    test** to a 371 kB app. That is not a trade, it is a different product.
 *  - It is **honestly not the real exam**, and the UI says so in those words:
 *    the voice is synthetic, and the real test uses recorded speakers with
 *    varied accents (British, Australian, North American, New Zealand) which a
 *    platform voice will not reproduce. See `SYNTHETIC_VOICE_NOTICE`.
 *  - Where the platform offers no usable voice, `TranscriptPaceDriver` reveals
 *    the transcript cue by cue at a fixed speaking pace rather than silently
 *    doing nothing — plan 011's STOP condition, discharged.
 *
 * ## Why there is an interface at all
 *
 * `SpeechDriver` exists so the runner can be tested **without a speech engine**.
 * `speechSynthesis` does not exist in jsdom or in Node, it is asynchronous, it
 * is famously flaky across platforms, and nothing about the play-once rule or
 * section ordering has anything to do with it. `FakeSpeechDriver` is
 * deterministic, uses no timers and records what it was asked to say, so the
 * engine tests can assert on playback without ever touching a browser global.
 *
 * Nothing in this file touches a global at import time. It is imported by tests
 * that run in the Node environment.
 */
import type { ListeningSection, ListeningVoiceHint } from './types'

/* ---------------------------------- notices --------------------------------- */

/**
 * What the UI must tell the learner about the audio, in plain words.
 *
 * Exported as a constant rather than typed into a component so that it cannot
 * quietly go missing: it is the honesty half of the audio decision, and a
 * Listening screen that plays a synthetic voice without saying so is
 * misrepresenting how close the practice is to the exam.
 */
export const SYNTHETIC_VOICE_NOTICE =
  'This voice is generated by your browser, not a recording. The real IELTS ' +
  'Listening test uses actors recorded in a studio, with British, Australian, ' +
  'North American and New Zealand accents. Treat this as practice for the ' +
  'question types and note-taking, not for accents.'

/** Shown when no usable voice exists and the transcript is revealed instead. */
export const TRANSCRIPT_FALLBACK_NOTICE =
  'Your browser has no speech voice available, so the transcript is being ' +
  'revealed line by line at speaking pace instead. This is a reading exercise ' +
  'with a clock on it, not a listening one — be aware of the difference.'

/* ----------------------------------- cues ----------------------------------- */

/** One thing to say, flattened out of a transcript for playback. */
export interface SpeechCue {
  /** `ListeningCue.id`. */
  id: string
  /** Speaker label to display, e.g. 'ROSS'. */
  speaker: string
  text: string
  /** Silence before this cue, in seconds. */
  pauseBeforeSec?: number
  /** How the speaker should sound, when the driver can honour it. */
  voice?: ListeningVoiceHint
}

/**
 * Flatten a section's transcript into a playback queue.
 *
 * Pure and total. A cue naming a speaker the section never declared is still
 * played — with its raw id as the label — rather than dropped: losing a line of
 * the recording because of a typo in a content file would cost the learner a
 * mark and give no clue why. `tests/listening-marking.test.ts` catches the typo
 * instead.
 */
export function sectionCues(section: ListeningSection): SpeechCue[] {
  const byId = new Map(section.transcript.speakers.map((speaker) => [speaker.id, speaker]))

  return section.transcript.cues.map((cue) => {
    const speaker = byId.get(cue.speakerId)
    return {
      id: cue.id,
      speaker: speaker?.label ?? cue.speakerId,
      text: cue.text,
      pauseBeforeSec: cue.pauseBeforeSec,
      voice: speaker?.voice,
    }
  })
}

/* --------------------------------- the driver -------------------------------- */

export type SpeechDriverKind = 'speech-synthesis' | 'transcript-pace' | 'fake'

/**
 * How a playback ended.
 *
 * `unavailable` is distinct from `cancelled` on purpose: the first means the
 * learner heard nothing through no fault of their own and the UI owes them an
 * explanation, the second means they stopped it.
 */
export type SpeechOutcome = 'completed' | 'cancelled' | 'unavailable'

/** Progress reports during playback. Every handler is optional. */
export interface SpeechEvents {
  onCueStart?: (cue: SpeechCue, index: number) => void
  onCueEnd?: (cue: SpeechCue, index: number) => void
  onOutcome?: (outcome: SpeechOutcome) => void
}

/**
 * Something that can say a queue of cues out loud, in order.
 *
 * Deliberately tiny. There is no pause, no seek and no rate control on the
 * interface because the exam has none of them: the recording plays once,
 * straight through. A driver that offered seeking would let a runner build a
 * feature the exam does not have.
 */
export interface SpeechDriver {
  readonly kind: SpeechDriverKind
  /** Can this driver actually produce output right now? */
  available(): boolean
  /**
   * Speak every cue in order. Resolves once the last one finishes, or as soon
   * as playback is cancelled or found to be impossible. Never rejects.
   */
  play(cues: readonly SpeechCue[], events?: SpeechEvents): Promise<SpeechOutcome>
  /** Stop immediately. Safe to call when nothing is playing. */
  cancel(): void
}

/* -------------------------------- scheduling -------------------------------- */

/**
 * Delayed execution, injectable so the paced driver can be driven by a fake
 * clock in a test rather than by real seconds.
 */
export interface SpeechScheduler {
  /** Run `fn` after `ms`. Returns a function that cancels it. */
  after(ms: number, fn: () => void): () => void
}

/** The real clock. */
export const realScheduler: SpeechScheduler = {
  after(ms, fn) {
    const handle: ReturnType<typeof setTimeout> = setTimeout(fn, ms)
    return () => clearTimeout(handle)
  },
}

/**
 * Speaking pace of the fallback driver, in words per minute.
 *
 * IELTS Listening recordings run at roughly 120–150 wpm depending on the
 * section and the speaker. 130 sits inside that band and is deliberately not
 * adjustable per cue: a fallback that let the learner slow the transcript down
 * would be training a skill the exam does not test.
 */
export const TRANSCRIPT_PACE_WPM = 130

/** How long a cue should take at a given pace. Zero for empty text. */
export function cueDurationMs(text: string, wordsPerMinute: number = TRANSCRIPT_PACE_WPM): number {
  const words = text.trim().split(/\s+/).filter((word) => word.length > 0).length
  if (words === 0) return 0

  const pace = wordsPerMinute > 0 ? wordsPerMinute : TRANSCRIPT_PACE_WPM
  return Math.round((words / pace) * 60_000)
}

/* -------------------------- browser speech synthesis ------------------------- */

/** The slice of `window.speechSynthesis` this module uses. */
export interface SpeechSynthesisLike {
  speak(utterance: SpeechSynthesisUtterance): void
  cancel(): void
  getVoices(): SpeechSynthesisVoice[]
}

/** The synthesiser plus the utterance constructor, injectable as a pair. */
export interface SpeechEngine {
  synthesis: SpeechSynthesisLike
  createUtterance(text: string): SpeechSynthesisUtterance
}

/**
 * The browser's engine, or null where there is not one.
 *
 * Reads its globals through `globalThis` inside the function body, so importing
 * this module in Node — which every engine test does — touches nothing.
 */
export function browserSpeechEngine(): SpeechEngine | null {
  const scope = globalThis as {
    speechSynthesis?: SpeechSynthesisLike
    SpeechSynthesisUtterance?: new (text: string) => SpeechSynthesisUtterance
  }

  const synthesis = scope.speechSynthesis
  const Utterance = scope.SpeechSynthesisUtterance
  if (synthesis === undefined || Utterance === undefined) return null

  return { synthesis, createUtterance: (text) => new Utterance(text) }
}

/**
 * Pick a voice for a cue.
 *
 * Best effort and nothing more. Platforms disagree about voice names, about how
 * many they expose and about when `getVoices()` starts returning any, so this
 * prefers an exact language match, falls back to the same primary language, and
 * otherwise lets the platform default speak. It never fails.
 */
export function pickVoice(
  voices: readonly SpeechSynthesisVoice[],
  hint: ListeningVoiceHint | undefined,
): SpeechSynthesisVoice | null {
  if (hint === undefined || voices.length === 0) return null

  const wanted = hint.accent.toLowerCase()
  const primary = wanted.split('-')[0]

  const exact = voices.find((voice) => voice.lang.toLowerCase().replace('_', '-') === wanted)
  if (exact !== undefined) return exact

  const sameLanguage = voices.find((voice) => voice.lang.toLowerCase().startsWith(primary))
  return sameLanguage ?? null
}

/**
 * Speaks through the browser.
 *
 * One utterance at a time, chained on `onend`, because queueing the whole
 * section into `speechSynthesis` at once loses the ability to report which cue
 * is being spoken and makes cancellation ragged. An utterance that errors is
 * treated as finished rather than fatal: one mangled line is better than a
 * section that stops halfway with no explanation.
 */
export class SpeechSynthesisDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'speech-synthesis'

  private engine: SpeechEngine | null
  private cancelled = false

  constructor(engine: SpeechEngine | null = browserSpeechEngine()) {
    this.engine = engine
  }

  available(): boolean {
    return this.engine !== null
  }

  cancel(): void {
    this.cancelled = true
    this.engine?.synthesis.cancel()
  }

  play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    const engine = this.engine
    if (engine === null) {
      events.onOutcome?.('unavailable')
      return Promise.resolve<SpeechOutcome>('unavailable')
    }

    this.cancelled = false

    return new Promise<SpeechOutcome>((resolve) => {
      const finish = (outcome: SpeechOutcome): void => {
        events.onOutcome?.(outcome)
        resolve(outcome)
      }

      const speakFrom = (index: number): void => {
        if (this.cancelled) return finish('cancelled')
        if (index >= cues.length) return finish('completed')

        const cue = cues[index]
        const utterance = engine.createUtterance(cue.text)
        const voice = pickVoice(engine.synthesis.getVoices(), cue.voice)
        if (voice !== null) utterance.voice = voice
        if (cue.voice?.rate !== undefined) utterance.rate = cue.voice.rate
        if (cue.voice?.pitch !== undefined) utterance.pitch = cue.voice.pitch

        let advanced = false
        const advance = (): void => {
          if (advanced) return
          advanced = true
          events.onCueEnd?.(cue, index)
          speakFrom(index + 1)
        }

        utterance.onend = advance
        // An engine error ends the line, not the section.
        utterance.onerror = advance

        events.onCueStart?.(cue, index)
        engine.synthesis.speak(utterance)
      }

      speakFrom(0)
    })
  }
}

/* ---------------------------- transcript fallback ---------------------------- */

/**
 * The fallback: reveal the transcript one cue at a time at a fixed pace.
 *
 * Plan 011's option C, used only where option B has no voice to work with. It
 * is honest about being a different exercise (`TRANSCRIPT_FALLBACK_NOTICE`) and
 * it holds the one property that makes it worth having: the learner cannot go
 * back, and the text moves on whether they are ready or not.
 */
export class TranscriptPaceDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'transcript-pace'

  private cancelTimer: (() => void) | null = null
  private cancelled = false

  constructor(
    private readonly scheduler: SpeechScheduler = realScheduler,
    private readonly wordsPerMinute: number = TRANSCRIPT_PACE_WPM,
  ) {}

  /** Always. Revealing text needs nothing from the platform. */
  available(): boolean {
    return true
  }

  cancel(): void {
    this.cancelled = true
    this.cancelTimer?.()
    this.cancelTimer = null
  }

  play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    this.cancelled = false

    return new Promise<SpeechOutcome>((resolve) => {
      const finish = (outcome: SpeechOutcome): void => {
        this.cancelTimer = null
        events.onOutcome?.(outcome)
        resolve(outcome)
      }

      const revealFrom = (index: number): void => {
        if (this.cancelled) return finish('cancelled')
        if (index >= cues.length) return finish('completed')

        const cue = cues[index]
        const pause = Math.max(0, (cue.pauseBeforeSec ?? 0) * 1000)
        const spoken = cueDurationMs(cue.text, this.wordsPerMinute)

        this.cancelTimer = this.scheduler.after(pause, () => {
          if (this.cancelled) return finish('cancelled')
          events.onCueStart?.(cue, index)

          this.cancelTimer = this.scheduler.after(spoken, () => {
            if (this.cancelled) return finish('cancelled')
            events.onCueEnd?.(cue, index)
            revealFrom(index + 1)
          })
        })
      }

      revealFrom(0)
    })
  }
}

/* ------------------------------- the test double ----------------------------- */

export interface FakeSpeechDriverOptions {
  /** Report no usable voice. Playback then speaks nothing. Defaults to true. */
  available?: boolean
  /** Cancel once this many cues have started, to exercise the cancelled path. */
  cancelAfterCues?: number
}

/**
 * A deterministic `SpeechDriver` for tests.
 *
 * No timers, no globals, no randomness: `play` walks the queue synchronously,
 * fires the same events a real driver fires, and resolves on the next
 * microtask. It records every cue it spoke and every outcome it reported, which
 * is what makes "the sections played in order, and each one reported
 * completion" an assertion rather than a hope.
 */
export class FakeSpeechDriver implements SpeechDriver {
  readonly kind: SpeechDriverKind = 'fake'

  /** Every cue actually spoken, across every `play` call, in order. */
  readonly spoken: SpeechCue[] = []
  /** One entry per `play` call, in call order. */
  readonly outcomes: SpeechOutcome[] = []
  /** One entry per `play` call: the cue ids it was handed. */
  readonly queues: string[][] = []

  private readonly isAvailable: boolean
  private readonly cancelAfterCues: number | null
  private cancelled = false

  constructor(options: FakeSpeechDriverOptions = {}) {
    this.isAvailable = options.available ?? true
    this.cancelAfterCues = options.cancelAfterCues ?? null
  }

  available(): boolean {
    return this.isAvailable
  }

  cancel(): void {
    this.cancelled = true
  }

  async play(cues: readonly SpeechCue[], events: SpeechEvents = {}): Promise<SpeechOutcome> {
    this.queues.push(cues.map((cue) => cue.id))

    if (!this.isAvailable) {
      this.outcomes.push('unavailable')
      events.onOutcome?.('unavailable')
      return 'unavailable'
    }

    this.cancelled = false
    let outcome: SpeechOutcome = 'completed'

    for (let index = 0; index < cues.length; index += 1) {
      if (this.cancelled) {
        outcome = 'cancelled'
        break
      }

      const cue = cues[index]
      events.onCueStart?.(cue, index)
      this.spoken.push(cue)

      if (this.cancelAfterCues !== null && this.spoken.length >= this.cancelAfterCues) {
        this.cancelled = true
      }

      if (this.cancelled) {
        outcome = 'cancelled'
        break
      }

      events.onCueEnd?.(cue, index)
    }

    this.outcomes.push(outcome)
    events.onOutcome?.(outcome)
    return outcome
  }

  /** The text of everything spoken so far, for assertions on content. */
  spokenText(): string[] {
    return this.spoken.map((cue) => cue.text)
  }
}

/* -------------------------------- construction ------------------------------- */

export interface CreateSpeechDriverOptions {
  /** Override the engine, e.g. to force the fallback. Defaults to the browser's. */
  engine?: SpeechEngine | null
  scheduler?: SpeechScheduler
  wordsPerMinute?: number
}

/**
 * The driver this platform can actually use: the browser's synthesiser where
 * there is one, the paced transcript where there is not.
 *
 * The choice is made once, at construction, and the caller can see which it got
 * from `driver.kind` — which is how the UI knows whether to show
 * `SYNTHETIC_VOICE_NOTICE` or `TRANSCRIPT_FALLBACK_NOTICE`.
 */
export function createSpeechDriver(options: CreateSpeechDriverOptions = {}): SpeechDriver {
  const engine = options.engine !== undefined ? options.engine : browserSpeechEngine()
  if (engine !== null) return new SpeechSynthesisDriver(engine)

  return new TranscriptPaceDriver(
    options.scheduler ?? realScheduler,
    options.wordsPerMinute ?? TRANSCRIPT_PACE_WPM,
  )
}

/** The notice a driver's kind obliges the UI to show. */
export function noticeFor(kind: SpeechDriverKind): string {
  return kind === 'transcript-pace' ? TRANSCRIPT_FALLBACK_NOTICE : SYNTHETIC_VOICE_NOTICE
}
